// Generated by scripts/register-partner-firebase-android.mjs
// Firebase project "upaharo" — partner Android app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static const bool isConfigured = true;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return android; // iOS partner app not configured yet
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMlexHg22gb_kCMpJGfhFtwPboaCOBgj4',
    appId: '1:733718052740:android:46fcd083b49c2bf5dd67d1',
    messagingSenderId: '733718052740',
    projectId: 'upaharo',
    storageBucket: 'upaharo.firebasestorage.app',
  );
}
